.travis.yml: fail build when code in before_script or script blocks fails.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,6 +9,7 @@ env:
     - secure: "fBav56BzY+A+Vs1g9YSfo1oLDCO1rFrXl49lJkOA5/XpnsKEEs4lI2RcOzz0wiJKXFNgcliiAJWoYMI8Esqz+lkyFWan4ij5Co0UzJcytDuY+2o+jaqwx45DuDYPogABzT+hWjLCxQLLG46gUkChzT8kcvOOn6JxC7Ff8q5MnoM="
 
 before_script:
+  - set -o errexit # exit immediately when commands return a non-zero status
   - if [ "$SPRING_PROFILES_ACTIVE" = 'travis' ]; then
       mysql -u travis -e 'CREATE DATABASE mystamps CHARACTER SET utf8;';
       mkdir -p /tmp/uploads /tmp/preview;
@@ -25,6 +26,7 @@ before_script:
     fi
 
 script:
+  - set -o errexit # exit immediately when commands return a non-zero status
   - if [ "$SPRING_PROFILES_ACTIVE" = 'travis' ]; then
       ./src/main/scripts/ci/check-build-and-verify.sh;
     else
