Run integration tests as another script execution to avoid exceeding the output buffer.
Addressed to #631

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -27,11 +27,15 @@ before_script:
     fi
 
 script:
-  - set -o errexit # exit immediately when commands return a non-zero status
+  # run all check analysis and unit tests only on travis profile
   - if [ "$SPRING_PROFILES_ACTIVE" = 'travis' ]; then
-      ./src/main/scripts/ci/check-build-and-verify.sh;
-    else
-      ./src/main/scripts/ci/check-build-and-verify.sh --only-integration-tests;
+      ./src/main/scripts/ci/check-build-and-verify.sh || FAIL_BUILD=yes;
+    fi
+  # run integration tests and danger on all profiles
+  - ./src/main/scripts/ci/check-build-and-verify.sh --only-integration-tests || FAIL_BUILD=yes;
+  # fail a build when one of the scripts have failed
+  - if [ -n "${FAIL_BUILD}" ]; then
+      exit 1;
     fi
 
 after_success:
