test: run integration tests with Python instead of Jython

diff --git a/.github/workflows/integration-tests-h2.yml b/.github/workflows/integration-tests-h2.yml
--- a/.github/workflows/integration-tests-h2.yml
+++ b/.github/workflows/integration-tests-h2.yml
@@ -54,11 +54,46 @@ jobs:
           # Whether to configure the token or SSH key with the local git config. Default: true
           persist-credentials: false
 
+      - name: Install mise to set up tools
+        uses: jdx/mise-action@v3.5.1 # https://github.com/jdx/mise-action
+        with:
+          version: 2025.11.11                # [default: latest] mise version to install
+          install: true                    # [default: true] run `mise install`
+          cache: true                      # [default: true] cache mise using GitHub's cache
+          log_level: info                  # [default: info] log level
+          working_directory: .             # [default: .] directory to run mise in
+        env:
+          # Workaround: don't install some dependencies that we don't want (java)
+          # See: https://github.com/jdx/mise-action/issues/183
+          # https://mise.jdx.dev/configuration/settings.html#disable_tools
+          MISE_DISABLE_TOOLS: java
+
       - name: Install JDK
         uses: actions/setup-java@v5.1.0 # https://github.com/actions/setup-java
         with:
           distribution: 'adopt'                    # https://github.com/actions/setup-java#supported-distributions
           java-version: ${{ matrix.java-version }} # https://github.com/actions/setup-java#supported-version-syntax
+
+      - name: Install Chrome
+        uses: browser-actions/setup-chrome@v2.1.1 # https://github.com/browser-actions/setup-chrome
+        with:
+          chrome-version: '145.0.7632.117' # Must match version in mise.toml
+          install-dependencies: false      # Default: false
+          install-chromedriver: false      # Default: false
+
+      - name: Install Robot Framework
+        run: pip install -r requirements.txt
+
+      # NOTE: robot --version returns 251 exit code
+      # See for details:
+      # - https://github.com/robotframework/robotframework/issues/5184
+      # - https://github.com/robotframework/robotframework/issues/3874
+      # - https://robotframework.org/robotframework/3.2.2/RobotFrameworkUserGuide.html#return-codes
+      - name: Show tools versions
+        run: |
+          robot --version || :
+          chrome --version
+          chromedriver --version
 
       - name: Restore existing cache
         uses: actions/cache@v5.0.2 # https://github.com/actions/cache
