chore: ensure that there are no modified files after terraform init
Trying to address the following case:
%
Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.
%

diff --git a/.github/workflows/provision-by-terraform.yml b/.github/workflows/provision-by-terraform.yml
--- a/.github/workflows/provision-by-terraform.yml
+++ b/.github/workflows/provision-by-terraform.yml
@@ -105,6 +105,15 @@ jobs:
           TF_IN_AUTOMATION: true
         run: terraform init
 
+      - name: Check whether there are no modified files
+        run: >-
+          MODIFIED_FILES="$(git status --short)";
+          if [ -n "$MODIFIED_FILES" ]; then
+            echo >&2 "ERROR: the following files have been modified:";
+            echo >&2 "$MODIFIED_FILES";
+            exit 1;
+          fi
+
       - name: Run terraform plan
         working-directory: infra/terraform
         env:
